EXTRA(24, "Why centralise: cross-cutting concerns and the internal 'core' library", {
  deep: [
    "A core package is imported by every service, so its import-time behaviour matters more than in a normal library. Nothing in core should connect to a database, read a file or start a thread when it is imported. Everything is wired by an explicit call such as configure_logging() or create_app(), so a unit test can import a module without network access. Core also must not pin exact versions of big frameworks; it declares ranges (fastapi>=0.110) and lets each service pin exact versions in its own lock file. If core pins fastapi==0.111.0 and a service needs 0.115, pip cannot resolve and the team is blocked.",
    "The hard part is the diamond problem. Service A depends on acme-core 3 and on acme-billing-sdk, and acme-billing-sdk depends on acme-core 2. Only one version of a package can be installed in one Python environment, so the resolver fails. The rule that avoids this is that internal SDKs depend on core with a wide range (acme-core>=2,<4) and never on an exact version, and that core removes a public function only after it has emitted a DeprecationWarning for at least two minor releases. Private modules (an underscore prefix) are free to change at any time, which is why the public surface of core is kept small on purpose.",
    "Do not centralise too early or too much. If only two teams need something, a shared snippet or a documented pattern is cheaper than a library with a release process. If a module in core gets business meaning (for example a Customer class), it will be changed by many teams and will become the slowest-moving code in the company. And do not put every convenience into one monolithic package: a service that only needs the HTTP client should not pull in Django. Split by extras first, and into separate packages (acme-core, acme-core-django, acme-core-celery) only when the release cycles really differ."
  ],
  iq: [
    { q: "A platform team wants to put retry logic into a shared library. Another engineer suggests a sidecar or service mesh instead. How do you decide?", a: "A library runs inside the process, so it can see application state, exceptions and types, and it works with no infrastructure change; but every service must upgrade to get a fix. A sidecar or mesh (Envoy, Istio) handles retries, timeouts and mTLS outside the process for every language at once, and is updated centrally; but it cannot know that a specific exception is safe to retry and it adds a network hop. Most large companies use both: the mesh for transport-level concerns and the library for anything that needs application knowledge." },
    { q: "How do you remove a function from a core library used by 50 services without breaking anyone?", a: "First ship a minor release that keeps the function but emits a DeprecationWarning pointing to the replacement, and make CI in the service template treat that warning as an error only on new code. Then search the company (a code search tool or a GitHub org-wide grep) for remaining callers and open pull requests for them. Remove the function only in the next major release, and keep the old major on a maintenance branch for security fixes for a defined time.", c: `
import warnings

def get_client(*args, **kwargs):
    warnings.warn("get_client() is deprecated; use acme_core.http.client() instead",
                  DeprecationWarning, stacklevel=2)
    return client(*args, **kwargs)
` },
    { q: "Service A needs acme-core 3 and an internal SDK that still requires acme-core<3. What are the options?", a: "Python can install only one version of a package per environment, so the install fails. Short term the team pins the SDK version that already works with core 3, or vendors the few SDK calls it needs. The real fix is a policy: internal SDKs must declare a wide core range and must be tested in CI against the oldest and newest supported core majors. This is the reason core should keep its public API small and stable." },
    { q: "What belongs in the core package and what does not? Give examples both ways.", a: "In: logging setup, request context, the error base classes and handlers, settings base class, HTTP client factory, auth dependency, metrics and tracing setup, health endpoints, Celery base task. Out: ORM models for business entities, pricing or tax logic, anything that needs a company database, feature code that only one team uses, and anything that changes weekly. A simple test is: would a brand new service in a different business unit want this unchanged? If not, it is not core." }
  ],
  tips: [
    "Publish core with optional extras and keep the base install tiny. A Celery worker installs acme-core[celery] and never sees FastAPI; a lambda function installs plain acme-core.",
    "Keep a CODEOWNERS file and a small review group for core, and a public CHANGELOG.md with Added, Changed, Deprecated and Removed sections for each version. Teams read the changelog before they upgrade, so write it for them.",
    "Run a nightly job that installs the main branch of core into three or four real services and runs their test suites. It finds breaking changes before a release, not after.",
    "Set up Renovate or Dependabot in every service repo to open an upgrade pull request when a new core version is published. The adoption curve is then measured in days, not quarters."
  ]
});

EXTRA(24, "Custom middleware in FastAPI and ASGI", {
  deep: [
    "When the first request arrives, Starlette calls build_middleware_stack() once and caches the result. The stack is, from outside to inside: ServerErrorMiddleware, then the user middleware in the order of app.user_middleware, then ExceptionMiddleware, then the Router. Because add_middleware() inserts at index 0 of user_middleware, the last one added becomes the outermost. Two consequences follow. First, calling add_middleware() after the first request raises RuntimeError, because the stack is already built. Second, the handlers you register with @app.exception_handler(HTTPException) live in ExceptionMiddleware, which is inside all user middleware. An HTTPException raised directly inside your own middleware is not seen by those handlers; it goes up to ServerErrorMiddleware and becomes a 500. Only the handler for Exception or 500 lives in ServerErrorMiddleware. That is why the body-size fast path in the example sends a response itself instead of raising.",
    "The scope dictionary is shared by every layer, so middleware can put values in it (scope['state'] is the official place, visible as request.state) and later layers can read them. Headers in scope are lower-case byte pairs; a wrong case or a str value is a silent bug. The response is a sequence of messages: one http.response.start with status and headers, then one or more http.response.body with more_body=True for streaming. Headers can only be changed on the start message, and once it has been sent the status code is final. A middleware that wants to measure full response time must therefore look at the last body message, not the start message. Request bodies arrive in chunks through receive(); the http.request message has more_body=True until the last chunk, which is why counting bytes in a wrapped receive works for uploads without buffering them.",
    "BaseHTTPMiddleware exists because the pure form is verbose. It runs call_next in a separate task group, which has side effects: a contextvar set by the endpoint is not visible after call_next returns, the response you get back is always a StreamingResponse whose body you cannot read without consuming it, and exceptions from background tasks surface in surprising places. These issues have been reduced over Starlette versions but not removed, so shared code uses pure ASGI. When should you not centralise? Behaviour that depends on the route, such as a per-endpoint rate limit or a permission check, belongs in a FastAPI dependency, not in middleware, because middleware runs before routing and knows nothing about the matched path operation."
  ],
  iq: [
    { q: "In FastAPI you add middleware A, then B, then C with app.add_middleware(). In which order do they run for a request?", a: "C, then B, then A on the way in, and A, B, C on the way out. add_middleware() inserts at the front of the list, so the last added is the outermost. If you need a fixed order across services, add them in one function in the core package and never let teams add middleware before calling it. app.middleware('http') decorators follow the same rule because they call add_middleware internally.", c: `
app.add_middleware(A)
app.add_middleware(B)
app.add_middleware(C)
# request:  ServerErrorMiddleware -> C -> B -> A -> ExceptionMiddleware -> router
` },
    { q: "Your middleware raises HTTPException(401) when a header is missing, but the client receives a 500. Why?", a: "The HTTPException handler lives in ExceptionMiddleware, which is inside the user middleware stack. An exception raised in your middleware never reaches it; it travels outward to ServerErrorMiddleware, which only knows how to produce a 500. The fix is to build and send the 401 response yourself in the middleware, or to move the check into a dependency where FastAPI's handlers apply." },
    { q: "Why is setting a contextvar inside BaseHTTPMiddleware.dispatch, after call_next, often useless?", a: "call_next runs the inner application in a separate task. Context variables are copied into a new task when it starts, so values set before call_next are visible downstream, but values set downstream are not visible to dispatch afterwards, and values set after call_next cannot affect the endpoint that already ran. For request-scoped context, set the variable before calling the inner app, in pure ASGI middleware, and reset it in a finally block." },
    { q: "How do you refuse a 2 GB upload without reading it into memory?", a: "Check the Content-Length header first and reject immediately with a 413 if it is above the limit; this costs nothing. Clients can omit or lie about Content-Length with chunked encoding, so also wrap receive() and count the bytes of every http.request message, stopping as soon as the total passes the limit. Never call request.body() in middleware to check the size, because that reads the whole thing." }
  ],
  tips: [
    "Put the request ID into scope['state'] as well as a contextvar. Route code reads it as request.state.request_id and log formatters read the contextvar; both stay in sync.",
    "Use the exact header name X-Request-ID across the whole company and configure the load balancer or ingress to generate it when missing. Then even the first log line of the first service has the same ID the client saw.",
    "Test pure ASGI middleware without a server: wrap a tiny async app that records what it received, and call the middleware with a hand-made scope dictionary. It runs in microseconds and needs no HTTP client.",
    "Keep middleware free of awaits on external systems (database, Redis). One slow call there delays every request in the service, including health checks. Do that work lazily in a dependency only for the routes that need it."
  ]
});

EXTRA(24, "Custom middleware and DRF customisation in Django", {
  deep: [
    "Django builds the middleware chain once at startup in BaseHandler.load_middleware(). It walks the MIDDLEWARE list in reverse, so the last entry wraps the view directly and the first entry is the outermost. Each middleware factory is called with the next get_response, which is why __init__ runs once and __call__ runs per request. Besides __call__, a middleware may define process_view (runs after URL resolution, before the view), process_exception (runs when the view raises) and process_template_response. Django also checks the sync_capable and async_capable attributes: under ASGI, a sync-only middleware forces a thread switch for every request, which costs performance and can break the use of contextvars across the boundary. Shared middleware should set both flags and be written to work in both modes.",
    "DRF plugs into Django at the view. APIView.dispatch() wraps the Django request in a rest_framework Request, then calls initial(), which runs in this order: content negotiation, version detection, perform_authentication, check_permissions, check_throttles. Every pluggable class is looked up through a method such as get_permissions(), which reads self.permission_classes, which defaults to api_settings.DEFAULT_PERMISSION_CLASSES. The api_settings object reads the REST_FRAMEWORK dictionary lazily and imports dotted paths on first access, so a wrong path fails on the first request, not at startup. When the view raises, handle_exception() first converts NotAuthenticated into a 401 or 403 depending on whether the first authenticator defines a WWW-Authenticate header, then calls the function named by EXCEPTION_HANDLER. If that function returns None, DRF re-raises and Django produces a 500 through its own handler500 path.",
    "There are limits to what the REST_FRAMEWORK dictionary can centralise. It cannot change the shape of a successful non-paginated response; that requires a custom renderer or a custom Response class. Permission objects are combined with the & and | operators because BasePermission defines __and__ and __or__ returning OperandHolder objects; has_object_permission is only called if you call self.check_object_permissions() or use get_object(), so a list view never triggers it. Throttles depend on the cache backend; with the default local memory cache every worker process has its own counter, so a limit of 1000 per hour really means 1000 per worker. The shared throttle must point at Redis. Finally, do not force one pagination style on views that stream exports or return single aggregates; allow pagination_class = None where it is honest."
  ],
  iq: [
    { q: "Why does the DRF EXCEPTION_HANDLER not catch an exception raised in a Django middleware?", a: "DRF's handler is called from APIView.handle_exception(), which only wraps the view method. Middleware runs outside the view in Django's own handler chain, so an exception there goes to Django's process_exception hooks and finally to the 500 handler. To get the same error JSON for both, the core package provides a Django middleware that catches exceptions and renders the same problem-details body that the DRF handler renders." },
    { q: "A view sets permission_classes = [IsAuthenticated, HasScope] and a user with the right scope but no login gets a 403, not a 401. Why?", a: "DRF decides between 401 and 403 by asking the first authentication class whether it has an authenticate_header(). Session authentication has none, so DRF returns 403 for unauthenticated requests. Token or JWT authentication returns a WWW-Authenticate value, and then DRF returns 401. The order of DEFAULT_AUTHENTICATION_CLASSES therefore changes status codes, which is a good reason to fix that order in core." },
    { q: "How do you make one error response format for all nine Django APIs in the company without editing each view?", a: "Three pieces in the shared package: an EXCEPTION_HANDLER function that reshapes DRF exceptions, a Django middleware with process_exception for errors outside the view, and custom handler404 and handler500 views for URLs that never reach DRF. All three render the same JSON shape from one function. Teams add five lines to settings; they do not touch views.", c: `
# acme_core/django/handlers.py
from django.http import JsonResponse

def problem(status, title, detail=None, **extra):
    body = {"type": "about:blank", "title": title, "status": status, "detail": detail, **extra}
    return JsonResponse(body, status=status, content_type="application/problem+json")

def handler404(request, exception=None):
    return problem(404, "Not Found", request.path)

def handler500(request):
    return problem(500, "Internal Server Error")
` },
    { q: "Why can a UserRateThrottle of 100/min allow far more than 100 requests in production?", a: "Throttle counters are stored with the Django cache framework. If the cache is the default LocMemCache, each gunicorn worker and each server has its own memory, so the limit applies per process. With 8 workers on 4 servers, the real limit is up to 3200 per minute. Point the throttle at a shared Redis cache (the throttle class has a cache attribute) and the limit becomes global." }
  ],
  tips: [
    "Ship the shared REST_FRAMEWORK dictionary from core and let projects extend it: REST_FRAMEWORK = {**CORE_REST_FRAMEWORK, 'DEFAULT_THROTTLE_RATES': {'user': '5000/hour'}}. One import keeps 40 projects in sync.",
    "Give every shared DRF class a name that says what it does, such as StandardPagination or HasScope, and set required_scope on views as a plain class attribute. Reviewers can then see the access rule without opening another file.",
    "Add a Django system check (django.core.checks) in core that fails startup when the project is missing RequestContextMiddleware or uses LocMemCache with throttling. Checks run in manage.py and in CI, so the mistake never reaches production.",
    "Pin the DRF versioning scheme company-wide (for example URLPathVersioning with /v1/). Mixed schemes across services make API gateways and generated clients much harder to configure."
  ]
});
